kind: Service
apiVersion: v1
metadata:
  name: user-app-svc
  labels:
    app: user-app
spec:
  selector:
    app: user-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: vijayrathor/user-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP